name: gallery-share

x-django: &django
  build: .
  working_dir: /app/
  # volumes:
  #   - ./app:/app
  env_file:
    - ./.env
  restart: always


services:
  app:
    <<: *django
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8001 --reload
    ports:
      - 18001:8001
    expose:
      - 8001
    environment:
      EMAIL_BACKEND: smtp
      EMAIL_HOST: mailpit
      EMAIL_PORT: 1025
      DEFAULT_FROM_EMAIL: "Photo Gallery <no-reply@localhost>"
    depends_on:
      - mailpit
    develop:
      watch:
        - action: sync+restart
          path: ./app/
          target: /app/

        - action: rebuild
          path: ./pyproject.toml

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./db.env
    healthcheck:
      test: pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 1s
      timeout: 5s
      retries: 10

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 18000:80
    depends_on:
      - app

  mailpit:
    image: axllent/mailpit:latest
    restart: always
    ports:
      - 18002:8025  # Web UI
      - 1025:1025   # SMTP

volumes:
  postgres_data:
