name: gallery-share

x-django: &django
  build: .
  working_dir: /app/
  volumes:
    - ./app:/app
  env_file:
    - ./.env
  restart: always


services:
  app:
    <<: *django
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8001 --reload
    ports:
      - 18001:8001
    expose:
      - 8001
    develop:
      # Create a `watch` configuration to update the app
      #
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment
          ignore:
            - .venv/

        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./pyproject.toml

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./db.env
    healthcheck:
      test: pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 1s
      timeout: 5s
      retries: 10

  nginx:
    build: ./nginx
    ports:
      - 18000:80
    depends_on:
      - app

volumes:
  postgres_data:
